name: Build and Release

on:
  push:
    branches: 
      - main
      - master
      - release/*
  pull_request:
    branches: ['*']
  
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            sys: MINGW64
          - os: windows-latest
            sys: UCRT64
          - os: windows-latest
            sys: CLANG64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install CMake (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Install CMake (macOS)
      if: runner.os == 'macOS'
      run: brew install cmake

    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          base-devel
          git
          cmake
        pacboy: >-
          cmake:p
          make:p
          cc:p
          7zip:p
    
    - name: Configure CMake (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: cmake --build build --config Release
      
    - name: Build (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: cmake --build build --config Release
    
    - name: Package build artifacts (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mkdir -p build/package
        cmake --install build --prefix build/package
        tar -czvf build/package.tar.gz build/package/*
        
    - name: Package build artifacts (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        mkdir -p build/package
        cmake --install build --prefix build/package
        7z a build/package.zip build/package/*
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-${{ matrix.sys || 'build' }}-${{ github.sha }}
        path: build/package.*
        if-no-files-found: error
    
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Determine release type
        id: release-type
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "RELEASE_TYPE=stable" >> $GITHUB_OUTPUT
            echo "TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_TYPE=pre-release" >> $GITHUB_OUTPUT
            echo "TAG=$(echo $GITHUB_REF | cut -d'/' -f3)-pre" >> $GITHUB_OUTPUT
          fi
          
      - name: Create GitHub Release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-type.outputs.TAG }}
          release_name: ${{ steps.release-type.outputs.TAG }}
          prerelease: ${{ steps.release-type.outputs.RELEASE_TYPE == 'pre-release' }}
          body: |
            Automated ${{ steps.release-type.outputs.RELEASE_TYPE }} build
            - OS: ${{ matrix.os }}
            - System: ${{ matrix.sys || 'native' }}
          draft: false
          generate_release_notes: true
          
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: artifacts/${{ runner.os }}-${{ matrix.sys || 'build' }}-${{ github.sha }}/*
          asset_name: ${{ runner.os }}-${{ matrix.sys || 'build' }}-${{ github.sha }}.zip
          asset_content_type: application/zip
